// This file is auto generated by Teams Toolkit to provide you instructions and reference code to implement single sign on.
// This file will use TeamsFx SDK to call Graph API to get user profile.
// Refer to this link to learn more: https://www.npmjs.com/package/@microsoft/teamsfx-react#calling-the-microsoft-graph-api.

import { Button } from "@fluentui/react-northstar";
import { TeamsFx } from "@microsoft/teamsfx";
import { useGraph } from "@microsoft/teamsfx-react";
import { Team } from "@microsoft/microsoft-graph-types";

export function GetUserMessage(props: { teamsfx?: TeamsFx }) {
  const { teamsfx } = {
    teamsfx: undefined,
    ...props,
  };

  // For usage of useGraph(), please refer to: https://www.npmjs.com/package/@microsoft/teamsfx-react#usegraph.
  const { loading, error, data, reload } = useGraph(
    async (graph, teamsfx, scope) => {
      // Call graph api use `graph` instance to get user profile information
      let response = await graph.api("/me/joinedTeams").get();
      let teams: Array<Team> = [];
      teams = response["value"];

      const names = []; 
      for(let i=0; i<teams.length; i++){
        const teamId = teams[i].id;
        const displayName = teams[i].displayName;
        names.push(displayName);
      }

      console.log(names);

      const teamOptions = names.map( name => {
        return(
          <li>
            {name}
          </li>
        );
      });

      console.log(teamOptions);

      return { teamOptions };
    },
    // Add scope for your Azure AD app. For example: Mail.Read, etc.
    // Use teamsfx instance from `InitTeamsFx`
    { scope: ["User.Read.All", "ChannelMessage.Read.All"], teamsfx: teamsfx }
  );

  return (
    <div>
      <h2>GetUserMessage</h2>
      <p>Click below to authorize button to grant permission to using Microsoft Graph.</p>
      <Button primary content="Authorize" disabled={loading} onClick={reload} />
      {!loading && error && (
        <div className="error">Failed to read your profile. Please try again later.</div>
      )}
      {!loading && data && <div> <ul>{data.teamOptions}</ul> </div>}
    </div>
  );
}
